Nama: Fadlan Sandi Albasith

Kelas: 2B

Nim: 25090049

1. buatlah sample menggunakan Stratified Random Sampling (By Genre) dari data berikut: https://drive.google.com/file/d/11FFr7HzsecBvA-4Of5bIySDKXAjY4X_O/view?usp=sharing

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [3]:
%cd "/content/drive/MyDrive/Kuliah/Semester 2/Statistika/Tugas Random Sampling dan T Distribusi/data_movie"

/content/drive/MyDrive/Kuliah/Semester 2/Statistika/Tugas Random Sampling dan T Distribusi/data_movie

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

data = pd.read_csv("MovieData-2018-2020.csv")
data

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,Midnight Sun,PG-13,Drama,2018,"March 23, 2018 (United States)",6.6,26000.0,Scott Speer,Kenji Bando,Bella Thorne,United States,2800000.0,2.736547e+07,Boies / Schiller Film Group,91.0
1,The House with a Clock in Its Walls,PG,Comedy,2018,"September 21, 2018 (United States)",6.1,48000.0,Eli Roth,John Bellairs,Jack Black,United States,42000000.0,1.315231e+08,DreamWorks,105.0
2,Peter Rabbit,PG,Animation,2018,"February 9, 2018 (United States)",6.6,38000.0,Will Gluck,Rob Lieber,James Corden,United States,50000000.0,3.514961e+08,Columbia Pictures,95.0
3,Rocketman,R,Biography,2019,"May 31, 2019 (United States)",7.3,153000.0,Dexter Fletcher,Lee Hall,Taron Egerton,United Kingdom,40000000.0,1.951793e+08,Paramount Pictures,121.0
4,Crawl,R,Action,2019,"July 12, 2019 (United States)",6.1,74000.0,Alexandre Aja,Michael Rasmussen,Kaya Scodelario,United States,13500000.0,9.154210e+07,Paramount Pictures,87.0
5,The Sun Is also a Star,PG-13,Drama,2019,"May 17, 2019 (United States)",5.9,6600.0,Ry Russo-Young,Tracy Oliver,Yara Shahidi,United States,9000000.0,6.750029e+06,Alloy Entertainment,100.0
6,Clinton Road,NaN,Horror,2019,"June 14, 2019 (United States)",5.9,1900.0,Richard Grieco,Noel Ashman,Ace Young,NaN,2500000.0,5.040000e+04,Growing Tree Productions,77.0
7,Searching,PG-13,Drama,2018,"August 31, 2018 (United States)",7.6,148000.0,Aneesh Chaganty,Aneesh Chaganty,John Cho,United States,880000.0,7.546204e+07,Screen Gems,102.0
8,Arctic,PG-13,Adventure,2018,"January 31, 2019 (Denmark)",6.8,46000.0,Joe Penna,Joe Penna,Mads Mikkelsen,Iceland,2000000.0,4.165776e+06,Armory Films,98.0
9,Ready or Not,R,Action,2019,"August 21, 2019 (United States)",6.9,121000.0,Matt Bettinelli-Olpin,Guy Busick,Samara Weaving,United States,6000000.0,5.761578e+07,Fox Searchlight Pictures,95.0
10,Halloween,R,Crime,2018,"October 19, 2018 (United States)",6.5,126000.0,David Gordon Green,John Carpenter,Jamie Lee Curtis,United States,10000000.0,2.556149e+08,Blumhouse Productions,106.0
11,Sonic the Hedgehog,PG,Action,2020,"February 14, 2020 (United States)",6.5,102000.0,Jeff Fowler,Pat Casey,Ben Schwartz,United States,85000000.0,3.197157e+08,Paramount Pictures,99.0
12,Wonder Park,PG,Animation,2019,"March 15, 2019 (United States)",5.9,11000.0,Dylan Brown,Josh Appelbaum,Sofia Mali,Spain,90000000.0,1.195591e+08,Paramount Animation,85.0
13,The Call of the Wild,PG,Adventure,2020,"February 21, 2020 (United States)",6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,Canada,135000000.0,1.111055e+08,20th Century Studios,100.0
14,Johnny English Strikes Again,PG,Action,2018,"October 26, 2018 (United States)",6.2,67000.0,David Kerr,William Davies,Rowan Atkinson,United Kingdom,25000000.0,1.589725e+08,Universal Pictures,89.0
15,The Death & Life of John F. Donovan,R,Drama,2018,"December 13, 2019 (United States)",6.2,5900.0,Xavier Dolan,Xavier Dolan,Kit Harington,Canada,35000000.0,3.326364e+06,Lyla Films,123.0
16,Child's Play,R,Drama,2019,"June 21, 2019 (United States)",5.8,47000.0,Lars Klevberg,Tyler Burton Smith,Tim Matheson,Canada,10000000.0,4.490707e+07,Orion Pictures,90.0
17,Andhadhun,Not Rated,Crime,2018,"October 5, 2018 (United States)",8.2,79000.0,Sriram Raghavan,Arijit Biswas,Ayushmann Khurrana,India,4500000.0,6.247534e+07,Matchbox Pictures,139.0
18,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
19,Night School,PG-13,Comedy,2018,"September 28, 2018 (United States)",5.6,38000.0,Malcolm D. Lee,Kevin Hart,Kevin Hart,United States,29000000.0,1.031059e+08,Hartbeat Productions,111.0
20,The Equalizer 2,R,Action,2018,"July 20, 2018 (United States)",6.7,141000.0,Antoine Fuqua,Richard Wenk,Denzel Washington,United States,62000000.0,1.904002e+08,Columbia Pictures,121.0
21,Black Wall Street Burning,R,Drama,2020,"February 7, 2020 (United States)",6.6,35.0,Marcus Brown,Dekoven Riggins,Dan Belcher,United States,5000.0,NaN,Notis Studio,78.0
22,Mile 22,R,Action,2018,"August 17, 2018 (United States)",6.1,72000.0,Peter Berg,Graham Roland,Mark Wahlberg,United States,50000000.0,6.630876e+07,STX Entertainment,94.0
23,Death Wish,R,Action,2018,"March 2, 2018 (United States)",6.3,67000.0,Eli Roth,Joe Carnahan,Bruce Willis,United States,30000000.0,4.956271e+07,Cave 76,107.0
24,Toy Story 4,G,Animation,2019,"June 21, 2019 (United States)",7.7,217000.0,Josh Cooley,John Lasseter,Tom Hanks,United States,200000000.0,1.073395e+09,Pixar Animation Studios,100.0
25,The Angry Birds Movie 2,PG,Animation,2019,"August 14, 2019 (United States)",6.4,24000.0,Thurop Van Orman,Peter Ackerman,Jason Sudeikis,Finland,65000000.0,1.477920e+08,Sony Pictures Animation,97.0
26,Missing Link,PG,Animation,2019,"April 12, 2019 (United States)",6.7,23000.0,Chris Butler,Chris Butler,Hugh Jackman,Canada,100000000.0,2.656571e+07,Annapurna Pictures,93.0
27,Rambo: Last Blood,R,Action,2019,"September 20, 2019 (United States)",6.1,87000.0,Adrian Grunberg,Matthew Cirulnick,Sylvester Stallone,United States,50000000.0,9.149035e+07,Lionsgate,89.0
28,The Invisible Man,R,Drama,2020,"February 28, 2020 (United States)",7.1,186000.0,Leigh Whannell,Leigh Whannell,Elisabeth Moss,Canada,7000000.0,1.431510e+08,Universal Pictures,124.0
29,Birds of Prey,R,Action,2020,"February 7, 2020 (United States)",6.1,190000.0,Cathy Yan,Christina Hodson,Margot Robbie,United States,84500000.0,2.018585e+08,Clubhouse Pictures (II),109.0

In [6]:
data['genre'].value_counts()

genre
Action       9
Drama        7
Animation    5
Comedy       2
Biography    2
Adventure    2
Crime        2
Horror       1
Name: count, dtype: int64

In [7]:
#hilangkan genre yang hanya berisi 1 judul
filtered_data = data.groupby('genre').filter(lambda x: len(x) > 1)
filtered_data['genre'].value_counts()

genre
Action       9
Drama        7
Animation    5
Comedy       2
Biography    2
Adventure    2
Crime        2
Name: count, dtype: int64

Pakailah hanya 30 data teratas dari hasil sampling

In [9]:
#stratified sample by genre
_, stratified_sample = train_test_split(
    filtered_data,
    test_size = 0.3,
    stratify = filtered_data ['genre'],
    random_state = 49
)
sample = stratified_sample.head(30)
data_budget = sample['budget']

print("Stratified Sampling (30 data teratas):\n", sample)

Stratified Sampling (30 data teratas):
                                    name rating      genre  year  \
7                             Searching  PG-13      Drama  2018
3                             Rocketman      R  Biography  2019
20                      The Equalizer 2      R     Action  2018
23                           Death Wish      R     Action  2018
8                                Arctic  PG-13  Adventure  2018
15  The Death & Life of John F. Donovan      R      Drama  2018
22                              Mile 22      R     Action  2018
1   The House with a Clock in Its Walls     PG     Comedy  2018
12                          Wonder Park     PG  Animation  2019

                              released  score     votes         director  \
7      August 31, 2018 (United States)    7.6  148000.0  Aneesh Chaganty
3         May 31, 2019 (United States)    7.3  153000.0  Dexter Fletcher
20       July 20, 2018 (United States)    6.7  141000.0    Antoine Fuqua
23       March 2, 2018 (United States)    6.3   67000.0         Eli Roth
8           January 31, 2019 (Denmark)    6.8   46000.0        Joe Penna
15   December 13, 2019 (United States)    6.2    5900.0     Xavier Dolan
22     August 17, 2018 (United States)    6.1   72000.0       Peter Berg
1   September 21, 2018 (United States)    6.1   48000.0         Eli Roth
12      March 15, 2019 (United States)    5.9   11000.0      Dylan Brown

             writer               star         country      budget  \
7   Aneesh Chaganty           John Cho   United States    880000.0
3          Lee Hall      Taron Egerton  United Kingdom  40000000.0
20     Richard Wenk  Denzel Washington   United States  62000000.0
23     Joe Carnahan       Bruce Willis   United States  30000000.0
8         Joe Penna     Mads Mikkelsen         Iceland   2000000.0
15     Xavier Dolan      Kit Harington          Canada  35000000.0
22    Graham Roland      Mark Wahlberg   United States  50000000.0
1     John Bellairs         Jack Black   United States  42000000.0
12   Josh Appelbaum         Sofia Mali           Spain  90000000.0

          gross              company  runtime
7    75462037.0          Screen Gems    102.0
3   195179299.0   Paramount Pictures    121.0
20  190400157.0    Columbia Pictures    121.0
23   49562710.0              Cave 76    107.0
8     4165776.0         Armory Films     98.0
15    3326364.0           Lyla Films    123.0
22   66308758.0    STX Entertainment     94.0
1   131523093.0           DreamWorks    105.0
12  119559110.0  Paramount Animation     85.0

In [10]:
stratified_sample.describe()

,year,score,votes,budget,gross,runtime
count,9.000000,9.000000,9.000000,9.000000e+00,9.000000e+00,9.000000
mean,2018.222222,6.555556,76877.777778,3.909778e+07,9.283192e+07,106.222222
std,0.440959,0.587603,57283.369702,2.779399e+07,7.155089e+07,13.254978
min,2018.000000,5.900000,5900.000000,8.800000e+05,3.326364e+06,85.000000
25%,2018.000000,6.100000,46000.000000,3.000000e+07,4.956271e+07,98.000000
50%,2018.000000,6.300000,67000.000000,4.000000e+07,7.546204e+07,105.000000
75%,2018.000000,6.800000,141000.000000,5.000000e+07,1.315231e+08,121.000000
max,2019.000000,7.600000,153000.000000,9.000000e+07,1.951793e+08,123.000000

Hitunglah Estimasi (Statistics - Estimating Population Means) Budget Film menggunakan data sample tadi

In [11]:
import scipy.stats as stats
import math

x_bar = data_budget.mean()
s = data_budget.std(ddof=1)  #menggunakan ddof=1 karena ini sebuah data sample
n = len(data_budget)
confidence_level = 0.95

# Calculate alpha, degress of freedom (df), the critical t-value,
# And the margin of error
alpha = (1 - confidence_level)
df = n - 1
standard_error = s / math.sqrt(n)
critical_t = stats.t.ppf(1 - alpha / 2, df)
margin_of_error = critical_t * standard_error

# Calculate the lower and upper bound of the confidence interval
lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

# Print the results
print("Critical t-value : {:.2f}".format(critical_t))
print("Margin of Error : {:.2f}".format(margin_of_error))
print("Confidence Interval : ({:.2f}, {:.2f})".format(lower_bound, upper_bound))
print("The {:.1%} confidence interval for the population mean is:".format(confidence_level))
print("between {:.2f} and {:.2f}".format(lower_bound, upper_bound))

Critical t-value : 2.31
Margin of Error : 21364354.23
Confidence Interval : (17733423.55, 60462132.01)
The 95.0% confidence interval for the population mean is:
between 17733423.55 and 60462132.01